### ISSUE TITLE
Doesn't Seem to Work with TC 8.X

### ISSUE THREAD

**Issue by ftkendrakuhl** [carlpett/xUnit-TeamCity#11]
I have TC 8.0.5 installed. I installed this plugin because this is where the plugins page lands me for xunit, but I understand my TC is out of date. After installing the plugin and creating a build step, I get the following error. Is this because the plugin is intended for TC 9 and up or have I mucked up my configuration? If it's because my TC is outdated, is there a solution for TC 8?

`[Step 1/8] java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: jetbrains.buildServer.util.CollectionsUtil.toStringArray(Ljava/util/Collection;)[Ljava/lang/String;
    at java.util.concurrent.FutureTask$Sync.innerGet(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at se.capeit.dev.xunittestrunner.FutureBasedBuildProcess.waitFor(FutureBasedBuildProcess.java:70)
    at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:59)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.BuildRunAction.doStages(BuildRunAction.java:70)
    at jetbrains.buildServer.agent.impl.BuildRunAction.runBuild(BuildRunAction.java:50)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:248)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:48)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:221)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: jetbrains.buildServer.util.CollectionsUtil.toStringArray(Ljava/util/Collection;)[Ljava/lang/String;
    at se.capeit.dev.xunittestrunner.XUnitBuildProcess.call(XUnitBuildProcess.java:62)
    at se.capeit.dev.xunittestrunner.XUnitBuildProcess.call(XUnitBuildProcess.java:19)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)`

**Comment by carlpett** [comment]
Hi!
Looks like I'm using a utility method from the TeamCity libraries which is not present in older versions. This usage was introduced in the latest version (1.1.1) of the plugin, so maybe you could try the older releases if a TC update is difficult? I haven't had an 8.0 environment to test with for quite a while, so I'm not sure if there are other places in the 1.1 range which don't work. I did some light testing with the first 1.0 of the plugin, though, and as I recall there were no immediate problems.

Please let me know if one of those versions work for you, and I will see if I can either skip using that library, or at the very least add some compatibility information in the README.

**Comment by ftkendrakuhl** [comment]
Using 1.1 seems to fix the issue with TC 8. Thanks a bunch!
