### ISSUE TITLE
java.lang.NullPointerException when getting runner requirements

### ISSUE THREAD

**Issue by ghost** [carlpett/xUnit-TeamCity#15]
full trace is 
Trace: java.lang.NullPointerException
          at se.capeit.dev.xunittestrunner.XUnitTestRunType.getRunnerSpecificRequirements(XUnitTestRunType.java:86)
          at jetbrains.buildServer.serverSide.impl.runType.RunTypeWithExtensionsImpl.getRunnerSpecificRequirements(RunTypeWithExtensionsImpl.java:27)
          at jetbrains.buildServer.serverSide.impl.SBuildRunnerDescriptorImpl.getRunTypeRequirements(SBuildRunnerDescriptorImpl.java:3)
          at jetbrains.buildServer.serverSide.impl.build.steps.BuildStartContextBase.getEnabledRequirements(BuildStartContextBase.java:28)
          at jetbrains.buildServer.serverSide.RawCompatibilityCalculator.matchRequirements(RawCompatibilityCalculator.java:42)
          at jetbrains.buildServer.serverSide.RawCompatibilityCalculator.calculateInternal(RawCompatibilityCalculator.java:18)
          at jetbrains.buildServer.serverSide.RawCompatibilityCalculator.access$000(RawCompatibilityCalculator.java:6)
          at jetbrains.buildServer.serverSide.RawCompatibilityCalculator$1.run(RawCompatibilityCalculator.java:1)
          at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl$2.run(SecurityContextImpl.java:1)
          at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAs(SecurityContextImpl.java:35)
          at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAs(SecurityContextImpl.java:10)
          at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAsSystem(SecurityContextImpl.java:34)
          at jetbrains.buildServer.serverSide.RawCompatibilityCalculator.calculateCompatibility(RawCompatibilityCalculator.java:10)
          at jetbrains.buildServer.serverSide.impl.BuildPromotionImpl$CandidatesCache.getCompatibilityMap(BuildPromotionImpl.java:23)
          at jetbrains.buildServer.serverSide.impl.BuildPromotionImpl.getCompatibilityMap(BuildPromotionImpl.java:894)
          at jetbrains.buildServer.serverSide.impl.BuildTypeImpl.doGetCompatibilityMap(BuildTypeImpl.java:856)
          at jetbrains.buildServer.serverSide.impl.BuildTypeImpl.getCompatibilityMap(BuildTypeImpl.java:262)
          at jetbrains.buildServer.controllers.buildType.RequirementsBean.<init>(RequirementsBean.java:9)
          at jetbrains.buildServer.controllers.admin.projects.EditableRequirementsBean.<init>(EditableRequirementsBean.java:12)
          at jetbrains.buildServer.controllers.admin.projects.EditableBuildTypeSettingsForm.reloadRequirementsBean(EditableBuildTypeSettingsForm.java:89)
          at jetbrains.buildServer.controllers.admin.projects.AdminEditRequirementsController.getModelAndView(AdminEditRequirementsController.java:18)
          at jetbrains.buildServer.controllers.admin.projects.AbstractEditBuildTypeController.doGet(AbstractEditBuildTypeController.java:51)
          at jetbrains.buildServer.controllers.BaseFormXmlController.doHandle(BaseFormXmlController.java:60)
          at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
          at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
          at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
          at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
          at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
          at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
          at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
          at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
          at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
          at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
          at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet.service(TeamCityDispatcherServlet.java:42)
          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
          at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
          at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
          at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
          at jetbrains.buildServer.web.DisableSessionIdFromUrlFilter.doFilter(DisableSessionIdFromUrlFilter.java:8)
          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
          at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
          at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
          at jetbrains.buildServer.diagnostic.web.DiagnosticFilter.doFilter(DiagnosticFilter.java:45)
          at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
          at jetbrains.buildServer.web.DependencyParametersCalculationContextFilter.doFilter(DependencyParametersCalculationContextFilter.java:1)
          at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
          at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
          at jetbrains.buildServer.web.DelegatingFilter.doFilter(DelegatingFilter.java:2)
          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
          at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
          at jetbrains.buildServer.web.ResponseFragmentFilter.doFilter(ResponseFragmentFilter.java:23)
          at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
          at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
          at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
          at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
          at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
          at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
          at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
          at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
          at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
          at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
          at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1757)
          at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1716)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
          at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
          at java.lang.Thread.run(Thread.java:745)

**Comment by ghost** [comment]
Looks like result of #13 fix

**Comment by carlpett** [comment]
Thanks for reporting!
Yes, probably that is the cause. Did you upgrade from a previous version of the plugin, or is this a first install? What are the settings of the build step that crashes?

**Comment by jjmatthews** [comment]
Hi, the plugin was upgraded to the latest version from 1.0 to 1.1.2. The exception occurs when clicking on the agent requirement link.

**Comment by carlpett** [comment]
@jjmatthews and @ekoshkin : I made a fix for build steps defined in 1.0. Those lack certain parameters due to them not being configurable at the time, but since I only shipped specific varieties of the test runner (MSIL/v4.0 and MSIL/v4.5 respectively) it is possible to determine what they should be.
Also added a better error management, so any similar issues will not crash, but display a message instead.

I published a new release 1.1.3 with this fix, could you give it a shot?

**Comment by PolarbearDK** [comment]
I can confirm that the 1.1.3 fixes the problem.

**Comment by carlpett** [comment]
@PolarbearDK Thanks!
