### ISSUE TITLE
Teamcity Version 10.0.1 and version 1.1.3a

### ISSUE THREAD

**Issue by minoseah629** [carlpett/xUnit-TeamCity#23]
Hello, 
I have TeamCity Version 10.0.1 with xunit teamcity plugin version 1.1.3a. 

I uploaded the plugin a month plus ago, but I guess the server never restarted to update the plugin. 

But now after some random maintenance reboot, Teamcity plugin 1.1.3a started being used. 

But when the build is occurring, the step for the unit tests execution throws an error. 

[16:10:15]E: Step 7/9: Tests (xUnit)
[16:10:15] :	 [Step 7/9] Runner parameters { Version = 1.9.2, runtime = .NET 4.0, platform = AnyCPU/MSIL}
[16:10:15] :	 [Step 7/9] Failed to run tests
[16:10:15]W:	 [Step 7/9] java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at se.capeit.dev.xunittestrunner.XUnitBuildProcess.call(XUnitBuildProcess.java:58)
	at se.capeit.dev.xunittestrunner.XUnitBuildProcess.call(XUnitBuildProcess.java:19)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

This occurred for two project using xunit 1.9.2 

I deleted version 1.1.3a and reverted back to 1.1.2 to allow builds to occur without failure. 

https://github.com/Jogge/xUnit-TeamCity

**Comment by carlpett** [comment]
Hi!
Version 1.1.3a was built of a fork of this project, and included some code which did not account for some fields being uninitialized if created with previous versions. I have since merged that fork, including a fix for your issue, but this is yet unreleased. I'm hoping to release a version 1.2 "soonish", but if you did not need any of the features from the fork (namely xUnit 2.2 support or parallel runs), I'd recommend sticking with 1.1.2 for now.

Sorry about this!
